# Generated by Django 4.1.4 on 2022-12-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ask',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ask',
            name='type',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='dimension',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dimension',
            name='weigh',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indicator',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='indicator',
            name='weigh',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='measurementcriterion',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='measurementcriterion',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scale',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='scale',
            name='interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scale',
            name='maxValue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scale',
            name='minValue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scale',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='scalelabel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='scalelabel',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='variable',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='variable',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
