# Generated by Django 4.1.4 on 2022-12-24 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_ask_answer_ask_question_ask_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='measurementCriterion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.measurementcriterion'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='indicators',
            field=models.ManyToManyField(to='Models.indicator'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='scale',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Models.scale'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='scale',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Models.scale'),
        ),
        migrations.AddField(
            model_name='measurementcriterion',
            name='indicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.indicator'),
        ),
        migrations.AddField(
            model_name='poll',
            name='asks',
            field=models.ManyToManyField(to='Models.ask'),
        ),
        migrations.AddField(
            model_name='respondent',
            name='polls',
            field=models.ManyToManyField(to='Models.poll'),
        ),
        migrations.AddField(
            model_name='scalelabel',
            name='scale',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Models.scale'),
        ),
        migrations.AddField(
            model_name='variable',
            name='dimensions',
            field=models.ManyToManyField(to='Models.dimension'),
        ),
        migrations.AddField(
            model_name='variable',
            name='scale',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Models.scale'),
        ),
    ]
