# Generated by Django 4.1.4 on 2022-12-24 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_ask_measurementcriterion_dimension_indicators_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('type', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='', max_length=1)),
                ('measurementCriterion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.measurementcriterion')),
            ],
        ),
        migrations.DeleteModel(
            name='Ask',
        ),
        migrations.AlterField(
            model_name='poll',
            name='asks',
            field=models.ManyToManyField(to='Models.question'),
        ),
    ]
