# Generated by Django 4.1.4 on 2022-12-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0004_question_delete_ask_alter_poll_asks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimension',
            options={},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={},
        ),
        migrations.AlterModelOptions(
            name='measurementcriterion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={},
        ),
        migrations.AlterModelOptions(
            name='respondent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scale',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scalelabel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='variable',
            options={},
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='asks',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='scale',
            old_name='maxValue',
            new_name='max_value',
        ),
        migrations.RenameField(
            model_name='scale',
            old_name='minValue',
            new_name='min_value',
        ),
        migrations.AlterField(
            model_name='variable',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
