# Generated by Django 4.1.4 on 2022-12-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0006_alter_measurementcriterion_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='measurementCriterion',
            new_name='measurement_Criterion',
        ),
        migrations.AlterField(
            model_name='dimension',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scalelabel',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
