# Generated by Django 4.1.4 on 2022-12-24 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0007_rename_measurementcriterion_question_measurement_criterion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='measurement_Criterion',
            new_name='measurement_criterion',
        ),
    ]
