# Generated by Django 4.1.4 on 2022-12-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0008_rename_measurement_criterion_question_measurement_criterion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
