# Generated by Django 4.1.4 on 2022-12-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0010_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
