# Generated by Django 4.1.4 on 2022-12-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0011_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
