# Generated by Django 4.1.4 on 2022-12-31 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0013_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 0, 42, 12, 365855), verbose_name='date published'),
        ),
    ]
