# Generated by Django 4.1.4 on 2022-12-30 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0013_alter_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='name',
            field=models.CharField(default='Encuesta Sin Nombre', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='tittle',
            field=models.CharField(default='Pregunta Sin Titulo', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 17, 51, 58, 984069), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=200),
        ),
    ]
