# Generated by Django 4.1.4 on 2022-12-30 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0014_poll_name_question_tittle_alter_question_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 18, 7, 10, 511972), verbose_name='date published'),
        ),
    ]
