# Generated by Django 4.1.4 on 2023-01-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0014_alter_question_pub_date'),
        ('Models', '0015_alter_question_pub_date'),
    ]

    operations = [
    ]
